server:
  port: 9010

spring:
  application:
    name: mdx-shop-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: mdx
        group: mdx
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:
#        - id: mdx-shop-user             #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: lb:ws://mdx-shop-user    #匹配后提供服务的路由地址
#          predicates:
#            - Path=/user/**      #断言，路径相匹配的进行路由
#
#        - id: mdx-shop-order
#          uri: lb://mdx-shop-order
#          predicates:
#            - Path=/order/**
#  main:
#    web-application-type: reactive

gateway:
  routes:
    config:
      data-id: gateway-routes  #动态路由
      group: shop
      namespace: mdx

# 这个是 jwt 的配置
jwt:
  tokenHeader: Authorization
  secret: mdx-secrt000001
  expiration: 604800 #秒
  prefix: Bearer

# 不用登录就可以访问的接口
allowed:
  paths: /mdx-shop-user/user/login

seata:
  tx-service-group: my_test_tx_group
  enabled: true
  registry:
    type: nacos
    nacos:
      application: mdx-seata-server  #注册在nacos服务名
      server-addr: localhost:8848
      group : mdx
      namespace: mdx #注册在nacos命名空间