server:
  port: 9091

spring:
  application:
    name: mdx-shop-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: mdx
        group: mdx

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/mdx_order?autoRec&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: nancy010511

  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

seata:
  tx-service-group: my_test_tx_group
  enabled: true
  registry:
    type: nacos
    nacos:
      application: mdx-seata-server  #注册在nacos服务名
      server-addr: localhost:8848
      group : mdx
      namespace: mdx #注册在nacos命名空间

feign:
  sentinel:
    enabled: true


